name: Deploy S3 XRCloud Stage

on:
  push:
    branches:
      - xrcloud-stage

jobs:
  deploy-s3-stage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install
        run: yarn --prefer-offline
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}

      - name: Build
        run: yarn build
        env:
          HUBS_SERVER: https://hubs-api.stage.xrcloud.belivvr.com
          RETICULUM_SERVER: https://hubs-api.stage.xrcloud.belivvr.com
          THUMBNAIL_SERVER: https://nearspark.hubs-alpha.belivvr.com
          CORS_PROXY_SERVER: https://cors.dev.xrcloud.belivvr.com
          MEDIA_SERVER: https://reticulum.stage.xrcloud.belivvr.com
          NON_CORS_PROXY_DOMAINS: hubs-alpha.belivvr.com.com,stage.xrcloud.belivvr.com,assets.stage.xrcloud.belivvr.com
          BASE_ASSETS_PATH: https://assets.stage.xrcloud.belivvr.com/spoke/
          ROUTER_BASE_PATH: /spoke
          GITHUB_REPO: spoke
          IS_MOZ: false

      - name: Deploy S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: assets.stage.xrcloud.belivvr.com/spoke
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          SOURCE_DIR: 'dist'

      - name: invalidate
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: E1ZBJWL3EQ9PQ4
          PATHS: '/spoke/*'
          AWS_REGION: 'ap-northeast-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
