name: Deploy S3 Alpha

on:
  push:
    branches:
      - alpha

jobs:
  deploy-s3-alpha:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install
        run: yarn

      - name: Build
        run: yarn build
        env:
          HUBS_SERVER: ${{ secrets.HUBS_SERVER_ALPHA }}
          RETICULUM_SERVER: ${{ secrets.RETICULUM_SERVER_ALPHA }}
          FARSPARK_SERVER: ${{ secrets.FARSPARK_SERVER_ALPHA }}
          THUMBNAIL_SERVER: ${{ secrets.THUMBNAIL_SERVER_ALPHA }}
          CORS_PROXY_SERVER: ${{ secrets.CORS_PROXY_SERVER_ALPHA }}
          NON_CORS_PROXY_DOMAINS: ${{ secrets.NON_CORS_PROXY_DOMAINS_ALPHA }}
          BASE_ASSETS_PATH: ${{ secrets.BASE_ASSETS_PATH_ALPHA }}
          ROUTER_BASE_PATH: /spoke
          GITHUB_REPO: spoke
          IS_MOZ: false

      - name: Deploy S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_ALPHA_BUCKET_ALPHA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          SOURCE_DIR: 'dist'
